language: node_js
node_js:
  - "6.1"

addons:
  sauce_connect: true

before_script:
  - npm install -g bower
  - npm install -g web-component-tester
  - bower install

script:
  - npm run-script testSauce

cache:
  directories:
    - bower_components
    - node_modules

notifications:
  email: false
