language: node_js
node_js:
  - "6.1"

script:
  - CI=true node scripts/test.js --env=jsdom --verbose --coverage
  - yarn run build

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false
